title: "Jonathan Bayikehya"
baseline: "Développeur Étudiant passionné"
description: "Développeur passionné par la technologie, les projets innovants et le partage de connaissances."

params:
  author: "Jonathan Bayikehya"
  github: "https://github.com/Jonathanbayikehya"
  email: "jonathanbayikehya1960@gmail.com"
  social:
    - name: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Jonathanbayikehya"
    - name: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "#"
    - name: "Twitter"
      icon: "fab fa-twitter"
      url: "#"

menu:
  main:
    - name: "Accueil"
      url: "/"
      weight: 1
    - name: "Projets"
      url: "/projets/"
      weight: 2
    - name: "Blog"
      url: "/blog/"
      weight: 3
    - name: "Contact"
      url: "/contact/"
      weight: 4
